[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/blog-sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/blog-rss.xml"
  [headers.values]
    Content-Type = "application/rss+xml; charset=utf-8"
